PokeriaCapstone/Models/T_Ingredienti.cs
namespace PokeriaCapstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    public partial class T_Ingredienti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Ingredienti()
        {
            T_RelazionePokeIngredienti = new HashSet<T_RelazionePokeIngredienti>();
        }

        [Key]
        public int IDIngrediente { get; set; }

        [Required]
        [StringLength(30)]
        [DisplayName("Nome Ingrediente")]
        public string NomeIngrediente { get; set; }

        [Required]
        [StringLength(20)]
        [DisplayName("Tipo Ingrediente")]
        public string TipoIngrediente { get; set; }

        [Column(TypeName = "money")]
        [DisplayName("Prezzo Aggiuntivo")]
        public decimal? PrezzoAggiuntivo { get; set; }


        [NotMapped]
        public HttpPostedFileBase Immagine { get; set; }

        [Required]
        [StringLength(150)]
        [DisplayName("Foto")]
        public string FotoIngrediente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RelazionePokeIngredienti> T_RelazionePokeIngredienti { get; set; }




    }
}

PokeriaCapstone/Controllers/T_IngredientiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PokeriaCapstone.Models;

namespace PokeriaCapstone.Views.Home
{
    //[Authorize(Roles = "Admin")]
    public class T_IngredientiController : Controller
    {
        private ModelDBContext db = new ModelDBContext();

        public ActionResult ListaIngredienti()
        {
            return View(db.T_Ingredienti.ToList());
        }

        // GET: T_Ingredienti
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreatePokeComposta() 
        {
            return View();
        }

        // GET: T_Ingredienti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Ingredienti t_Ingredienti = db.T_Ingredienti.Find(id);
            if (t_Ingredienti == null)
            {
                return HttpNotFound();
            }
            return View(t_Ingredienti);
        }

        // GET: T_Ingredienti/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(T_Ingredienti t_Ingredienti)
        {
            t_Ingredienti.FotoIngrediente = "";

                if (t_Ingredienti.Immagine != null && t_Ingredienti.Immagine.ContentLength > 0) 
                {
                    var immagine = Path.GetFileName(t_Ingredienti.Immagine.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Assets/FotoIngredienti/"), immagine);
                    t_Ingredienti.Immagine.SaveAs(path);

                    t_Ingredienti.FotoIngrediente = immagine;
                }
                db.T_Ingredienti.Add(t_Ingredienti);
                db.SaveChanges();
                return RedirectToAction("ListaIngredienti");

        }

        // GET: T_Ingredienti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Ingredienti t_Ingredienti = db.T_Ingredienti.Find(id);
            if (t_Ingredienti == null)
            {
                return HttpNotFound();
            }
            return View(t_Ingredienti);
        }

        // POST: T_Ingredienti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDIngrediente,NomeIngrediente,TipoIngrediente,PrezzoAggiuntivo,FotoIngrediente")] T_Ingredienti t_Ingredienti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Ingredienti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t_Ingredienti);
        }

    

        // POST: T_Ingredienti/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Ingredienti t_Ingredienti = db.T_Ingredienti.Find(id);
            db.T_Ingredienti.Remove(t_Ingredienti);
            db.SaveChanges();
            return RedirectToAction("ListaIngredienti");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private class Ingrediente
        {
            public int Id { get; set; }
            public string Nome { get; set; }
            public string Tipo { get; set; }
            public decimal Prezzo { get; set; }
            public string Foto { get; set; }
        }

        public JsonResult GetBasi()
        {
            List<Ingrediente>IngredientiBase = new List<Ingrediente>();

            foreach (T_Ingredienti basi in db.T_Ingredienti.ToList())
                IngredientiBase.Add(new Ingrediente
                {
                    Id = basi.IDIngrediente,
                    Nome = basi.NomeIngrediente,
                    Tipo = basi.TipoIngrediente,
                    Prezzo = (decimal)basi.PrezzoAggiuntivo,
                    Foto = basi.FotoIngrediente
                });
            return Json(IngredientiBase.Where(i => i.Tipo == "Base").ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProteine()
        {
            List<Ingrediente> IngredientiProteine = new List<Ingrediente>();

            foreach (T_Ingredienti basi in db.T_Ingredienti.ToList())
                IngredientiProteine.Add(new Ingrediente
                {
                    Id = basi.IDIngrediente,
                    Nome = basi.NomeIngrediente,
                    Tipo = basi.TipoIngrediente,
                    Prezzo = (decimal)basi.PrezzoAggiuntivo,
                    Foto = basi.FotoIngrediente
                });
            return Json(IngredientiProteine.Where(i => i.Tipo == "Proteina").ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetContorni()
        {
            List<Ingrediente> IngredientiContorno = new List<Ingrediente>();

            foreach (T_Ingredienti basi in db.T_Ingredienti.ToList())
                IngredientiContorno.Add(new Ingrediente
                {
                    Id = basi.IDIngrediente,
                    Nome = basi.NomeIngrediente,
                    Tipo = basi.TipoIngrediente,
                    Prezzo = (decimal)basi.PrezzoAggiuntivo,
                    Foto = basi.FotoIngrediente
                });
            return Json(IngredientiContorno.Where(i => i.Tipo == "Contorno").ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTopping()
        {
            List<Ingrediente> IngredientiTopping = new List<Ingrediente>();

            foreach (T_Ingredienti basi in db.T_Ingredienti.ToList())
                IngredientiTopping.Add(new Ingrediente
                {
                    Id = basi.IDIngrediente,
                    Nome = basi.NomeIngrediente,
                    Tipo = basi.TipoIngrediente,
                    Prezzo = (decimal)basi.PrezzoAggiuntivo,
                    Foto = basi.FotoIngrediente
                });
            return Json(IngredientiTopping.Where(i => i.Tipo == "Topping").ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSalse()
        {
            List<Ingrediente> IngredientiSalse = new List<Ingrediente>();

            foreach (T_Ingredienti basi in db.T_Ingredienti.ToList())
                IngredientiSalse.Add(new Ingrediente
                {
                    Id = basi.IDIngrediente,
                    Nome = basi.NomeIngrediente,
                    Tipo = basi.TipoIngrediente,
                    Prezzo = (decimal)basi.PrezzoAggiuntivo,
                    Foto = basi.FotoIngrediente
                });
            return Json(IngredientiSalse.Where(i => i.Tipo == "Salsa").ToList(), JsonRequestBehavior.AllowGet);
        }


    }
}

PokeriaCapstone/Controllers/T_OrdiniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PokeriaCapstone.Models;

namespace PokeriaCapstone.Controllers
{
    public class T_OrdiniController : Controller
    {
        private ModelDBContext db = new ModelDBContext();


        public ActionResult Index()
        {
            int idUser = Convert.ToInt32(Session["IDUser"]);
            List<T_Ordini> listaOrdini = db.T_Ordini.Where(d => d.DataOrdine == null && d.FKIDUser == idUser).ToList();
            return View(listaOrdini);
        }

        public ActionResult OrdersForAdmin()
        {
            List<T_Ordini> listaOrdiniAdmin = db.T_Ordini.OrderByDescending(d => d.DataOrdine).ToList();
            return View(listaOrdiniAdmin);
        }

        public JsonResult TodaysOrders()
        {
            List<T_Ordini> ListaOrdiniOdierni = new List<T_Ordini>();
            foreach (T_Ordini ordine in db.T_Ordini.ToList())
                ListaOrdiniOdierni.Add(new T_Ordini
                {
                    IDOrdine = ordine.IDOrdine,
                    FKIDUser = ordine.FKIDUser,
                    FKIDPoke = ordine.FKIDPoke,
                    DataOrdine = ordine.DataOrdine,
                });
   
                return Json(ListaOrdiniOdierni.Where(o => o.DataOrdine == DateTime.Today).ToList(), JsonRequestBehavior.AllowGet);
        }



        public ActionResult ConfermaOrdine()
        {
            int idUser = Convert.ToInt32(Session["IDUser"]);
            foreach (T_Ordini ordine in db.T_Ordini.Where(d => d.DataOrdine == null && d.FKIDUser == idUser))
            {
                ordine.DataOrdine = DateTime.Now;
            }
            db.SaveChanges();
            ViewBag.OrdineConfermato = "Grazie mille! Il pagamento é andato a buon fine e il tuo ordine verrá consegnato il prima possibile!";
            return RedirectToAction("Index", "Home");
            
        }



        // GET: T_Ordini/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Ordini t_Ordini = db.T_Ordini.Find(id);
            if (t_Ordini == null)
            {
                return HttpNotFound();
            }
            return View(t_Ordini);
        }

        // GET: T_Ordini/Create
        public ActionResult Create()
        {
            ViewBag.FKIDPoke = new SelectList(db.T_Poke, "IDPoke", "NomePoke");
            ViewBag.FKIDUser = new SelectList(db.T_User, "IDUser", "Username");
            return View();
        }

        // POST: T_Ordini/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDOrdine,FKIDUser,FKIDPoke,DataOrdine")] T_Ordini t_Ordini)
        {
            if (ModelState.IsValid)
            {
                db.T_Ordini.Add(t_Ordini);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FKIDPoke = new SelectList(db.T_Poke, "IDPoke", "NomePoke", t_Ordini.FKIDPoke);
            ViewBag.FKIDUser = new SelectList(db.T_User, "IDUser", "Username", t_Ordini.FKIDUser);
            return View(t_Ordini);
        }

        // GET: T_Ordini/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Ordini t_Ordini = db.T_Ordini.Find(id);
            if (t_Ordini == null)
            {
                return HttpNotFound();
            }
            ViewBag.FKIDPoke = new SelectList(db.T_Poke, "IDPoke", "NomePoke", t_Ordini.FKIDPoke);
            ViewBag.FKIDUser = new SelectList(db.T_User, "IDUser", "Username", t_Ordini.FKIDUser);
            return View(t_Ordini);
        }

        // POST: T_Ordini/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDOrdine,FKIDUser,FKIDPoke,DataOrdine")] T_Ordini t_Ordini)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Ordini).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FKIDPoke = new SelectList(db.T_Poke, "IDPoke", "NomePoke", t_Ordini.FKIDPoke);
            ViewBag.FKIDUser = new SelectList(db.T_User, "IDUser", "Username", t_Ordini.FKIDUser);
            return View(t_Ordini);
        }

        // POST: T_Ordini/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Ordini t_Ordini = db.T_Ordini.Find(id);
            db.T_Ordini.Remove(t_Ordini);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PokeriaCapstone/Views/T_Ingredienti/Create.cshtml
@model PokeriaCapstone.Models.T_Ingredienti

@{
    ViewBag.Title = "Create";
}
<section class="mySection">
    <br />
    <h2 class="text-center">Aggiungi un nuovo ingrediente</h2>


    @using (Html.BeginForm("Create", "T_Ingredienti", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group d-flex align-items-center mb-2">
                @Html.LabelFor(model => model.NomeIngrediente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomeIngrediente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeIngrediente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group d-flex align-items-center mb-2">
                @Html.LabelFor(model => model.TipoIngrediente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TipoIngrediente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TipoIngrediente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group d-flex align-items-center mb-2">
                @Html.LabelFor(model => model.PrezzoAggiuntivo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrezzoAggiuntivo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrezzoAggiuntivo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group d-flex align-items-center mb-2">
                @Html.LabelFor(model => model.Immagine, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Immagine">
                    @Html.ValidationMessageFor(model => model.Immagine, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 mt-3">
                    <input type="submit" value="Aggiungi Ingrediente" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PokeriaCapstone/Views/T_Ingredienti/Delete.cshtml
@model PokeriaCapstone.Models.T_Ingredienti

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>T_Ingredienti</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeIngrediente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeIngrediente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoIngrediente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoIngrediente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrezzoAggiuntivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrezzoAggiuntivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoIngrediente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoIngrediente)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PokeriaCapstone/Views/T_Ingredienti/Index.cshtml
@model IEnumerable<PokeriaCapstone.Models.T_Ingredienti>

@{
    ViewBag.Title = "Index";
}

<br />
<br />
<section class="d-flex  align-items-center mySection flex-column">
    <div class="text-center">
        <h2 class="text-center text-light fw-bold">Seleziona una base</h2>
    </div>
    
    <div id="divBasi" class="row row-cols-4 gap-2 align-items-baseline">
    </div>
</section>


<section class="d-flex justify-content-center align-items-center mySection flex-column" id="ProteinsSection">
    <div class="text-center">
        <h3 class="text-center text-light fw-bold">Seleziona una proteina</h3>
    </div>
    <a href="ProteinsAnchor"></a>
    <div id="divProteine" class="row row-cols-4 gap-2 align-items-baseline mb-5">
    </div>
</section>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<section class="d-flex justify-content-center align-items-center mySection flex-column mb-5" id="ContorniSection">
    <div class="text-center">
        <h3 class="text-center text-light fw-bold">Seleziona fino a quattro contorni</h3>
    </div>
    <div id="divContorni" class="row row-cols-4 gap-2 align-items-baseline">
    </div>
</section>

<br />
<br />
<br />
<br />
<br />


<section class="d-flex align-items-center mySection flex-column" id="ToppingSection">
    <div class="text-center">
        <h3 class="text-center text-light fw-bold">Seleziona un topping</h3>
    </div>
    <div id="divTopping" class="row row-cols-4 gap-2 align-items-baseline">
    </div>
</section>                                                      
                                                                
                            
<section class="d-flex justify-content-center align-items-center mySection flex-column" id="SalseSection">
    <div class="text-center">
        <h3 class="text-center text-light fw-bold">Seleziona una salsa</h3>
    </div>
    <div id="divSalse" class="row row-cols-4 gap-2 align-items-baseline">
    </div>

        <div class="d-flex justify-content-center mt-5">
            <button class="btn btn-success" onclick="AddPoke()"> Crea la tua Poke</button>
        </div>

</section>


@section scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "GetBasi",
                success: function (data) {
                    console.log(data)
                    $.each(data, function (i, item) {
                        let div = "<div class='card col bg-transparent border-none mt-3' price='" + item.Prezzo + "' type='" + item.Tipo + "'style='width: 18rem;'>" +
                            "<img class='card-img-top ingredientPic' id='" + item.Id + "'  src='/Content/Assets/FotoIngredienti/" + item.Foto + "'/>" +
                            "<div class='card-body'>" +
                            "<h3 class='card-title text-center'>" + item.Nome + "</h3>" +
                            "<p class='card-text text-center'> Prezzo aggiuntivo:" + item.Prezzo + "€</p>" +
                            "</div>" +
                            "<div class='d-flex justify-content-around'>" +
                            "<a class='btn btn-primary add' onclick=addToPoke(" + item.Id + ")> Aggiungi </a>" +
                            "<a class='btn btn-danger' onclick=removeFromPoke(" + item.Id + ")> Rimuovi </a>" +
                            "</div>" +
                            "</div>"
                        $("#divBasi").append(div)

                    })
                }
            })
        })
    </script>
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "GetProteine",
                success: function (data) {
                    console.log(data)
                    $.each(data, function (i, item) {
                        let div = "<div class='card col bg-transparent border-none mt-3' price='" + item.Prezzo + "' type='" + item.Tipo + "'style='width: 18rem;'>" +
                            "<img class='card-img-top ingredientPic' id='" + item.Id + "'  src='/Content/Assets/FotoIngredienti/" + item.Foto + "'/>" +
                            "<div class='card-body'>" +
                            "<h3 class='card-title text-center'>" + item.Nome + "</h3>" +
                            "<p class='card-text text-center'> Prezzo aggiuntivo:" + item.Prezzo + "€</p>" +
                            "</div>" +
                            "<div class='d-flex justify-content-around'>" +
                            "<a class='btn btn-primary add' onclick=addToPoke(" + item.Id + ")> Aggiungi </a>" +
                            "<a class='btn btn-danger' onclick=removeFromPoke(" + item.Id + ")> Rimuovi </a>" +
                            "</div>" +
                            "</div>"
                        $("#divProteine").append(div)

                    })
                }
            })
        })
    </script>
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "GetContorni",
                success: function (data) {
                    console.log(data)
                    $.each(data, function (i, item) {
                        let div = "<div class='card col bg-transparent border-none mt-3' price='" + item.Prezzo + "' type='" + item.Tipo + "'style='width: 18rem;'>" +
                            "<img class='card-img-top ingredientPic' id='" + item.Id + "'  src='/Content/Assets/FotoIngredienti/" + item.Foto + "'/>" +
                            "<div class='card-body'>" +
                            "<h3 class='card-title text-center'>" + item.Nome + "</h3>" +
                            "<p class='card-text text-center'> Prezzo aggiuntivo:" + item.Prezzo + "€</p>" +
                            "</div>" +
                            "<div class='d-flex justify-content-around'>" +
                            "<a class='btn btn-primary add' onclick=addToPoke(" + item.Id + ")> Aggiungi </a>" +
                            "<a class='btn btn-danger' onclick=removeFromPoke(" + item.Id + ")> Rimuovi </a>" +
                            "</div>" +
                            "</div>"
                        $("#divContorni").append(div)
                    })
                }
            })
        })
    </script>
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "GetTopping",
                success: function (data) {
                    console.log(data)
                    $.each(data, function (i, item) {
                        let div = "<div class='card col bg-transparent border-none mt-3' price='" + item.Prezzo + "' type='" + item.Tipo + "'style='width: 18rem;'>" +
                            "<img class='card-img-top ingredientPic' height='' id='" + item.Id + "'  src='/Content/Assets/FotoIngredienti/" + item.Foto + "'/>" +
                            "<div class='card-body'>" +
                            "<h3 class='card-title text-center'>" + item.Nome + "</h3>" +
                            "<p class='card-text text-center'> Prezzo aggiuntivo:" + item.Prezzo + "€</p>" +
                            "</div>" +
                            "<div class='d-flex justify-content-around'>" +
                            "<a class='btn btn-primary add' onclick=addToPoke(" + item.Id + ")> Aggiungi </a>" +
                            "<a class='btn btn-danger' onclick=removeFromPoke(" + item.Id + ")> Rimuovi </a>" +
                            "</div>" +
                            "</div>"
                        $("#divTopping").append(div)

                    })
                }
            })
        })
    </script>
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "GetSalse",
                success: function (data) {
                    console.log(data)
                    $.each(data, function (i, item) {
                        let div = "<div class='card col bg-transparent border-none mt-3' price='" + item.Prezzo + "' type='" + item.Tipo + "'style='width: 18rem;'>" +
                            "<img class='card-img-top ingredientPic' id='" + item.Id + "'  src='/Content/Assets/FotoIngredienti/" + item.Foto + " '/>" +
                            "<div class='card-body'>" +
                            "<h3 class='card-title text-center'>" + item.Nome + "</h3>" +
                            "<p class='card-text text-center'> Prezzo aggiuntivo:" + item.Prezzo + "€</p>" +
                            "</div>" +
                            "<div class='d-flex justify-content-around'>" +
                            "<a class='btn btn-primary add' onclick=addToPoke(" + item.Id + ")> Aggiungi </a>" +
                            "<a class='btn btn-danger' onclick=removeFromPoke(" + item.Id + ")> Rimuovi </a>" +
                            "</div>" +
                            "</div>"
                        $("#divSalse").append(div)

                    })
                }
            })
        })
    </script>
    <script src="~/Scripts/AggiuntaIngredientiPoke.js">
    </script>
    <script>
        function AddPoke() {
            console.log(AddedPrices, SelectedItems)
            $.ajax({
                method: 'POST',
                url: "../T_Poke/CreateNewPokeComposta",
                data: { Prezzi: JSON.stringify(AddedPrices), Ingredienti: JSON.stringify(SelectedItems) },
                success: function (item) {
                    console.log(item)
                    location.href = "@Url.Action("Index", "T_Ordini", new { area = "" })"
                },
                error: function (e) {
                    console.log(e)
                },
            })
        }

    </script>


}