PokeriaCapstone/Controllers/T_PokeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Newtonsoft.Json;
using PokeriaCapstone.Models;

namespace PokeriaCapstone.Controllers
{
    
    public class T_PokeController : Controller
    {
        private ModelDBContext db = new ModelDBContext();

        // GET: T_Poke
        public ActionResult Index()
        {
            return View(db.T_Poke.ToList());
        }

        // GET: T_Poke/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Poke t_Poke = db.T_Poke.Find(id);
            if (t_Poke == null)
            {
                return HttpNotFound();
            }
            return View(t_Poke);
        }

        // GET: T_Poke/Create
        public ActionResult Create()
        {
            return View();
        }


        public ActionResult RecapPoke()
        {
            return View();
        }

        public ActionResult CreatePokeMaxi()
        {
            return View();
        }

        

        [HttpPost]
        public ActionResult CreateNewPokeComposta(string Prezzi, string Ingredienti)
        {
            List<decimal> PrezziList = JsonConvert.DeserializeObject<List<decimal>>(Prezzi);
            List<int> IngredientiList = JsonConvert.DeserializeObject<List<int>>(Ingredienti);
            decimal PrezzoTotale = 11;
            foreach (decimal prezzo in PrezziList)
            {
                PrezzoTotale += prezzo;
            }
            T_Poke Poke = new T_Poke("La tua poke", true, PrezzoTotale, "");
            db.T_Poke.Add(Poke);
            db.SaveChanges();
            foreach (int ingrediente in IngredientiList)
            {
                db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
                {
                    FKIDPoke = Poke.IDPoke,
                    FKIDIngrediente = ingrediente,
                });
            }
            db.SaveChanges();
            T_Ordini Ordine = new T_Ordini(Convert.ToInt32(Session["IDUser"]), Poke.IDPoke);
            db.T_Ordini.Add(Ordine);
            db.SaveChanges();

            return RedirectToAction("Index", "T_Ordini");
        }

        [HttpPost]
        public ActionResult CreateNewPokeCompostaMaxi(string Prezzi, string Ingredienti)
        {
            List<decimal> PrezziList = JsonConvert.DeserializeObject<List<decimal>>(Prezzi);
            List<int> IngredientiList = JsonConvert.DeserializeObject<List<int>>(Ingredienti);
            decimal PrezzoTotale = 13;
            foreach (decimal prezzo in PrezziList)
            {
                PrezzoTotale += prezzo;
            }
            T_Poke Poke = new T_Poke("La tua poke", true, PrezzoTotale, "");
            db.T_Poke.Add(Poke);
            db.SaveChanges();
            foreach (int ingrediente in IngredientiList)
            {
                db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
                {
                    FKIDPoke = Poke.IDPoke,
                    FKIDIngrediente = ingrediente,
                });
            }
            db.SaveChanges();
            T_Ordini Ordine = new T_Ordini(Convert.ToInt32(Session["IDUser"]), Poke.IDPoke);
            db.T_Ordini.Add(Ordine);
            db.SaveChanges();

            return RedirectToAction("Index", "T_Ordini");
        }

        // GET: T_Poke/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Poke t_Poke = db.T_Poke.Find(id);
            if (t_Poke == null)
            {
                return HttpNotFound();
            }
            return View(t_Poke);
        }

        // POST: T_Poke/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDPoke,NomePoke,IsComposta,Prezzo,FotoPoke")] T_Poke t_Poke)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Poke).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t_Poke);
        }

      
        [HttpGet]
        public ActionResult DeleteConfirmed(int id)
        {
            
            foreach (T_RelazionePokeIngredienti relazione in db.T_RelazionePokeIngredienti.Where(r => r.FKIDPoke == id))
            {
                db.T_RelazionePokeIngredienti.Remove(relazione);
            }
            foreach (T_Ordini ordine in db.T_Ordini.Where(o => o.FKIDPoke == id))
            {
                db.T_Ordini.Remove(ordine);
            }
            T_Poke t_Poke = db.T_Poke.Find(id);
            db.T_Poke.Remove(t_Poke);
            db.SaveChanges();
            return RedirectToAction("MenuForAdmin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        [HttpGet]
        public ActionResult CreatePokeMenu() 
        {
            List<SelectListItem> IngredientiList = new List<SelectListItem>(); 
            foreach (T_Ingredienti ingrediente in db.T_Ingredienti.ToList()) 
                IngredientiList.Add(new SelectListItem { Text = ingrediente.NomeIngrediente, Value = ingrediente.IDIngrediente.ToString() }); 
            ViewBag.Ingredienti = IngredientiList;
            return View();
        }

        [HttpPost]
        public ActionResult CreatePokeMenu(PokeMenu pokeMenu)
        {
            try
            {
                pokeMenu.FotoPokeMenu = "";
                if (pokeMenu.Immagine != null && pokeMenu.Immagine.ContentLength > 0)
                {
                    var immagine = Path.GetFileName(pokeMenu.Immagine.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Assets/FotoPokeMenu/"), immagine);
                    pokeMenu.Immagine.SaveAs(path);

                    pokeMenu.FotoPokeMenu = immagine;
                }
            }
            catch { } 

            T_Poke PokeToAdd = new T_Poke();

            PokeToAdd.NomePoke = pokeMenu.NomePokeMenu;
            PokeToAdd.IsComposta = false;
            PokeToAdd.FotoPoke = pokeMenu.Immagine.FileName;
            PokeToAdd.Prezzo = Convert.ToDecimal(pokeMenu.Prezzo);

            db.T_Poke.Add(PokeToAdd);


            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.BasePokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.ProteinaPokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.Contorno1PokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.Contorno2PokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.Contorno3PokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.Contorno4PokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.ToppingPokeMenu,
            });

            db.T_RelazionePokeIngredienti.Add(new T_RelazionePokeIngredienti
            {
                FKIDPoke = PokeToAdd.IDPoke,
                FKIDIngrediente = pokeMenu.SalsaPokeMenu,
            }) ;

            db.SaveChanges();

            Session["CreationComplete"] = "Poke correttamente inserita nel menu";

            return RedirectToAction("Menu");
        }

        public ActionResult Menu()
        {
            List<T_Poke> Menu = db.T_Poke.Where(p => p.IsComposta == false).ToList();
            return View(Menu);
        }

        public ActionResult AddToCart(int id)
        {
            int idUser = Convert.ToInt32(Session["IDUser"]);
            db.T_Ordini.Add(new T_Ordini
            {
                FKIDUser = idUser,
                FKIDPoke = id,
                DataOrdine = null
            }); 
            db.SaveChanges();
            return RedirectToAction("Index", "T_Ordini");
        }

        public ActionResult MenuForAdmin()
        {
            List<T_Poke> Menu = db.T_Poke.Where(p => p.IsComposta == false).ToList();
            return View(Menu);
        }


    }
}

PokeriaCapstone/Views/T_Poke/Create.cshtml
@model PokeriaCapstone.Models.T_Poke

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>T_Poke</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomePoke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomePoke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomePoke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsComposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsComposta)
                    @Html.ValidationMessageFor(model => model.IsComposta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoPoke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoPoke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoPoke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PokeriaCapstone/Views/T_Poke/CreatePokeMenu.cshtml
@model PokeriaCapstone.Models.PokeMenu

@{
    ViewBag.Title = "CreatePokeMenu";
}
<br />
<h2 class="text-center text-light">Aggiunta Poke al Menú</h2>



@using (Html.BeginForm("CreatePokeMenu", "T_Poke", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.NomePokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.EditorFor(model => model.NomePokeMenu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomePokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Immagine, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            <input type="file" name="Immagine">
            @Html.ValidationMessageFor(model => model.Immagine, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.BasePokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.BasePokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona la Base", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.BasePokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.ProteinaPokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.ProteinaPokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona la Proteina", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.ProteinaPokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Contorno1PokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.Contorno1PokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona il primo contorno", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.Contorno1PokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Contorno2PokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.Contorno2PokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona il secondo contorno", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.Contorno2PokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Contorno3PokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.Contorno3PokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona il terzo contorno", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.Contorno3PokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.Contorno4PokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.Contorno4PokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona il quarto contorno", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.Contorno4PokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.ToppingPokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.ToppingPokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona il topping", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.ToppingPokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-2 d-flex align-items-center">
        @Html.LabelFor(model => model.SalsaPokeMenu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 ms-3">
            @Html.DropDownListFor(model => model.SalsaPokeMenu, new SelectList(ViewBag.Ingredienti, "Value", "Text"), "Seleziona la salsa", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.SalsaPokeMenu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mt-3 pb-4">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

PokeriaCapstone/Views/T_Poke/Delete.cshtml
@model PokeriaCapstone.Models.T_Poke

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>T_Poke</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomePoke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomePoke)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComposta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComposta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoPoke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoPoke)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PokeriaCapstone/Views/T_Poke/Details.cshtml
@model PokeriaCapstone.Models.T_Poke

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>T_Poke</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomePoke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomePoke)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComposta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComposta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoPoke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoPoke)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDPoke }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PokeriaCapstone/Views/T_Poke/Edit.cshtml
@model PokeriaCapstone.Models.T_Poke

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>T_Poke</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDPoke)

        <div class="form-group">
            @Html.LabelFor(model => model.NomePoke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomePoke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomePoke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsComposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsComposta)
                    @Html.ValidationMessageFor(model => model.IsComposta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoPoke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoPoke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoPoke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PokeriaCapstone/Views/T_Poke/Index.cshtml
@model IEnumerable<PokeriaCapstone.Models.T_Poke>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomePoke)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsComposta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FotoPoke)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomePoke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsComposta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FotoPoke)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDPoke }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDPoke }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IDPoke })
        </td>
    </tr>
}

</table>

PokeriaCapstone/Views/T_Poke/Menu.cshtml
@model IEnumerable<PokeriaCapstone.Models.T_Poke>

@{
    ViewBag.Title = "Menu";
}
<br />
<div>
    <h2 class="text-center mt-3 text-light fw-bold">Menu</h2>
</div>

<div class="row row-cols-lg-3 row-cols-sm-1 gap-5 d-flex justify-content-center pb-5">
    @foreach (var item in Model)
    {
        <div class="col d-flex justify-content-evenly cardSingleOrder p-3">
            <div class="d-flex flex-column align-items-center">
                <div class="bg-danger p-3 rounded-4">
                    <h2 class="text-center text-warning">@item.NomePoke</h2>
                </div>
                <div class="d-flex justify-content-center">
                    <img src="~/Content/Assets/FotoPokeMenu/@item.FotoPoke" alt="foto poke Menu" width="150" height="150" />
                </div>
                <div>
                    <h2>
                        Prezzo:
                    </h2>
                </div>
                <div>
                    <h3>
                        @Html.DisplayFor(model => item.Prezzo)
                    </h3>
                </div>
            </div>

            <div class="align-self-center">
                <div class="d-flex justify-content-center">
                    <ul>
                        @foreach (var ingrediente in item.T_RelazionePokeIngredienti)
                        {
                            <li>
                                @ingrediente.T_Ingredienti.NomeIngrediente
                            </li>
                        }
                    </ul>
                </div>
                <div class="d-flex justify-content-center mb-2">
                    <a @Html.ActionLink("Aggiungi al carrello", "AddToCart", new { @id = item.IDPoke }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    }
</div>

PokeriaCapstone/Views/T_Poke/MenuForAdmin.cshtml
@model IEnumerable<PokeriaCapstone.Models.T_Poke>

@{
    ViewBag.Title = "MenuForAdmin";
}
<section class="mySection">
    <br />
    <h2 class="text-center">Gestione Menu</h2>

    <a href="/T_Poke/CreatePokeMenu" class="btn btn-success mb-3">
        Inserisci una Poke nel Menú
    </a>
    <table class="table mb-0">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomePoke)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezzo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FotoPoke)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomePoke)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezzo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FotoPoke)
                </td>
                <td>
                    @Html.ActionLink("Elimina dal Menú", "DeleteConfirmed", "T_Poke", new { id = item.IDPoke }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</section>

PokeriaCapstone/Views/T_Poke/RecapPoke.cshtml
@model IEnumerable<PokeriaCapstone.Models.T_Poke>

@{
    ViewBag.Title = "RecapPoke";
}

<h2>RecapPoke</h2>

@if (Session["IDUser"] != null)
            {

            }

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomePoke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsComposta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FotoPoke)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDPoke }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDPoke }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IDPoke })
        </td>
    </tr>
}

</table>